export const ADD_QRCODE = 'ADD_QRCODE';
export const ADD_QRCODE_SUCCESS = 'ADD_QRCODE_SUCCESS';
export const ADD_QRCODE_FAIL = 'ADD_QRCODE_FAIL';
export const MARK_COLORED_ITEM = 'MARK_COLORED_ITEM';

export const FOUND_QRCODE_DATA = 'FOUND_QRCODE_DATA';

export const CLEAN_QRCODE = 'CLEAN_QRCODE';
export const CLEAN_COLORED_QRCODE = 'CLEAN_COLORED_QRCODE';

export const CLEAN_VALIDATED_QRCODE = 'CLEAN_VALIDATED_QRCODE';

export const ADD_COLORED_QRCODE = 'ADD_COLORED_QRCODE';
export const ADD_COLORED_QRCODE_SUCCESS = 'ADD_COLORED_QRCODE_SUCCESS';
export const ADD_COLORED_QRCODE_FAIL = "ADD_COLORED_QRCODE_FAIL";
export const SHOW_START_QRCODE = "SHOW_START_QRCODE";

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const FILTERED_BY_ID = 'FILTERED_BY_ID';
export const ITEM_VALIDATED_STATE = 'ITEM_VALIDATED_STATE';
